from typing import TypedDict


class GraphRAGState(TypedDict):
    """
    Type definition for the GraphRAG application state.
    """
    question: str # User question
    cypher_query: str # Neo4j Cypher Query generated by LLM
    graph_context: str # Graph context from Neo4j database
    answer: str # The final answer generated by the LLM
